-- WOOPT_USER TABLE CONTAINS THE INFORMATION ABOUT WOOPT'S USER PROFILE
CREATE TABLE IF NOT EXISTS WOOPT_USER (
  USER_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_FIRSTNAME VARCHAR(45) DEFAULT NULL,
  USER_LASTNAME VARCHAR(45) DEFAULT NULL,
  USER_DOB DATE DEFAULT NULL,
  USER_GENDER CHAR(1) DEFAULT NULL,
  USER_PHONE VARCHAR(45) DEFAULT NULL,
  USER_MOBILE VARCHAR(45) DEFAULT NULL,
  USER_PROFILE_PHOTO BLOB,
  USER_EMAIL VARCHAR(45) DEFAULT NULL,
  USER_PASSWORD VARCHAR(25) DEFAULT NULL,
  USER_LOGIN_MODE CHAR(1) DEFAULT NULL,
  ADDRESS_ID INT(11) DEFAULT NULL,
  USER_AUTHORIZATION INT(1) DEFAULT NULL,
  USER_CREATED_DATETIME DATETIME DEFAULT NULL,
  USER_LAST_UPDATE_DATETIME DATETIME DEFAULT NULL,
  DEVICE_ID VARCHAR(96) DEFAULT NULL,
  USER_STATUS INT(1) DEFAULT NULL,
  PRIMARY KEY (USER_ID)
);

-- 
CREATE TABLE IF NOT EXISTS WOOPT_USER_INFO (
  USER_INFO_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT(11) DEFAULT NULL,
  USER_INFO_LAST_LOGON DATETIME DEFAULT NULL,
  USER_INFO_NO_OF_LOGONS INT(11) DEFAULT NULL,
  USER_INFO_STATUS VARCHAR(45) DEFAULT NULL,
  USER_INFO_NOTIFICATION_FLAG INT(1) DEFAULT NULL,
  CREATED_DATETIME DATETIME DEFAULT NULL,
  LAST_UPDATED_DATETIME DATETIME DEFAULT NULL,
  USER_INFO_LASTLOGON_LATITUDE VARCHAR(45) DEFAULT NULL,
  USER_INFO_LASTLOGON_LONGITUDE VARCHAR(45) DEFAULT NULL,
  USER_INFO_CURRENT_LATITUDE VARCHAR(45) DEFAULT NULL,
  USER_INFO_CURRENT_LONGITUDE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (USER_INFO_ID)
);


CREATE TABLE IF NOT EXISTS WOOPT_SHOP_TO_CATEGORIES (
  SHOP_TO_CATEGORIES_ID INT(11) NOT NULL AUTO_INCREMENT,
  SHOP_ID INT(11) DEFAULT NULL,
  CATEGORY_ID INT(11) DEFAULT NULL,
  SHOP_TO_CATEGORIES_STATUS INT(1) DEFAULT NULL,
  PRIMARY KEY (SHOP_TO_CATEGORIES_ID)
);


CREATE TABLE IF NOT EXISTS WOOPT_SHOP_REVIEW (
  SHOP_REVIEW_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT(11) DEFAULT NULL,
  SHOP_ID INT(11) DEFAULT NULL,
  SHOP_REVIEW_USER_NAME VARCHAR(45) DEFAULT NULL,
  SHOP_REVIEW_USER_PHONE VARCHAR(45) DEFAULT NULL,
  SHOP_REVIEW_USER_CITY VARCHAR(45) DEFAULT NULL,
  SHOP_REVIEW_DESCRIPTION VARCHAR(200) DEFAULT NULL,
  SHOP_REVIEW_DATETIME DATETIME DEFAULT NULL,
  SHOP_REVIEW_READS INT(11) DEFAULT NULL,
  SHOP_REVIEW_SHOP_RATING INT(1) DEFAULT NULL,
  SHOP_REVIEW_LIKES_NO INT(11) DEFAULT NULL,
  LAST_UPDATED_DATETIME DATETIME DEFAULT NULL,
  PRIMARY KEY (SHOP_REVIEW_ID)
);


CREATE TABLE IF NOT EXISTS WOOPT_SHOP_INFO (
  SHOP_INFO_ID INT(11) NOT NULL AUTO_INCREMENT,
  SHOP_ID INT(11) DEFAULT NULL,
  SHOP_OPEN_STATUS INT(1) DEFAULT NULL,
  SHOP_OPENING_HOURS VARCHAR(45) DEFAULT NULL,
  SHOP_MAIN_CATEGORY VARCHAR(45) DEFAULT NULL,
  SHOP_CATEGORIES VARCHAR(45) DEFAULT NULL,
  SHOP_DESCRIPTION VARCHAR(45) DEFAULT NULL,
  SHOP_CHAT_STATUS INT(1) DEFAULT NULL,
  SHOP_FACEBOOK VARCHAR(96) DEFAULT NULL,
  CREATED_DATETIME DATETIME DEFAULT NULL,
  LAST_UPDATED_DATETIME DATETIME DEFAULT NULL,
  PRIMARY KEY (SHOP_INFO_ID)
);


CREATE TABLE IF NOT EXISTS WOOPT_SHOP_EMPLOYEE (
  SHOP_EMPLOYEE_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT(11) DEFAULT NULL,
  SHOP_ID INT(11) DEFAULT NULL,
  SHOP_EMPLOYEE_STATUS INT(1) DEFAULT NULL,
  SHOP_EMPLOYEE_ROLE VARCHAR(45) DEFAULT NULL,
  CREATED_DATETIME DATETIME DEFAULT NULL,
  LAST_UPDATED_DATETIME DATETIME DEFAULT NULL,
  PRIMARY KEY (SHOP_EMPLOYEE_ID)
);


CREATE TABLE IF NOT EXISTS WOOPT_SHOP_BRANCHES (
  SHOP_BRANCHES_ID INT(11) NOT NULL AUTO_INCREMENT,
  SHOP_ID INT(11) DEFAULT NULL,
  SHOP_BRANCHES_SHOP_ID INT(11) DEFAULT NULL,
  SHOP_BRANCHES_STATUS INT(1) DEFAULT NULL,
  SHOP_BRANCHES_MANAGER_ID INT(11) DEFAULT NULL,
  CREATED_DATETIME DATETIME DEFAULT NULL,
  LAST_UPDATED_DATETIME DATETIME DEFAULT NULL,
  PRIMARY KEY (SHOP_BRANCHES_ID)
);


CREATE TABLE IF NOT EXISTS WOOPT_SHOP (
  SHOP_ID INT(11) NOT NULL AUTO_INCREMENT,
  SHOP_NAME VARCHAR(45) DEFAULT NULL,
  SHOP_PROPRIETOR_ID INT(11) DEFAULT NULL,
  SHOP_PHONE VARCHAR(45) DEFAULT NULL,
  SHOP_MOBILE VARCHAR(45) DEFAULT NULL,
  SHOP_PROFILE_PHOTO BLOB,
  SHOP_PHOTOS BLOB,
  SHOP_EMAIL VARCHAR(45) DEFAULT NULL,
  SHOP_ADDRESS_ID INT(11) DEFAULT NULL,
  SHOP_VERIFICATION_STATUS INT(1) DEFAULT NULL,
  SHOP_STATUS VARCHAR(45) DEFAULT NULL,
  SHOP_ISPARENT CHAR(1) DEFAULT NULL,
  SHOP_PARENT_ID INT(11) DEFAULT NULL,
  SHOP_QR_CODE VARCHAR(96) DEFAULT NULL,
  SHOP_TYPE VARCHAR(45) DEFAULT NULL,
  SHOP_SUBCRIPTION_TYPE VARCHAR(45) DEFAULT NULL,
  CREATED_DATETIME DATETIME DEFAULT NULL,
  LAST_UPDATED_DATETIME DATETIME DEFAULT NULL,
  PRIMARY KEY (SHOP_ID)
);


CREATE TABLE IF NOT EXISTS WOOPT_FAMILY (
  FAMILY_ID INT(11) NOT NULL AUTO_INCREMENT,
  FAMILY_HEAD_ID INT(11) DEFAULT NULL,
  FAMILY_MEMBER_ID INT(11) DEFAULT NULL,
  FAMILY_MEMBER_STATUS INT(1) DEFAULT NULL,
  PRIMARY KEY (FAMILY_ID)
);


CREATE TABLE IF NOT EXISTS WOOPT_DEVICE (
  DEVICE_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT(11) DEFAULT NULL,
  DEVICE_IMEI VARCHAR(96) DEFAULT NULL,
  DEVICE_MAC VARCHAR(45) DEFAULT NULL,
  DEVICE_SERIAL_NO VARCHAR(96) DEFAULT NULL,
  DEVICE_STATUS INT(1) DEFAULT NULL,
  DEVICE_TOKEN VARCHAR(96) DEFAULT NULL,
  DEVICE_PHONE VARCHAR(45) DEFAULT NULL,
  DEVICE_OTP VARCHAR(45) DEFAULT NULL,
  DEVICE_OTP_STATUS INT(11) DEFAULT NULL,
  DEVICE_OTP_TIMESTAMP DATETIME DEFAULT NULL,
  CREATED_DATETIME DATETIME DEFAULT NULL,
  LAST_UPDATED_DATETIME DATETIME DEFAULT NULL,
  PRIMARY KEY (DEVICE_ID)
);


CREATE TABLE IF NOT EXISTS WOOPT_ADDRESS (
  ADDRESS_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT(11) DEFAULT NULL,
  SHOP_ID INT(11) DEFAULT NULL,
  ADDRESS_NAME VARCHAR(45) DEFAULT NULL,
  ADDRESS_STREET1 VARCHAR(45) DEFAULT NULL,
  ADDRESS_STREET2 VARCHAR(45) DEFAULT NULL,
  ADDRESS_AREA VARCHAR(45) DEFAULT NULL,
  ADDRESS_CITY VARCHAR(45) DEFAULT NULL,
  ADDRESS_STATE VARCHAR(45) DEFAULT NULL,
  ADDRESS_POSTCODE VARCHAR(45) DEFAULT NULL,
  ADDRESS_COUNTRY VARCHAR(45) DEFAULT NULL,
  ADDRESS_ZONE VARCHAR(45) DEFAULT NULL,
  ADDRESS_LATITUDE VARCHAR(45) DEFAULT NULL,
  ADDRESS_LONGITUDE VARCHAR(45) DEFAULT NULL,
  ADDRESS_LANDMARK VARCHAR(45) DEFAULT NULL,
  CREATED_DATETIME VARCHAR(45) DEFAULT NULL,
  LAST_UPDATED_DATETIME VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ADDRESS_ID)
);